project_id = "hddnqgggjjlildufirof"

# Set domain-router as the main handler
[functions._default]
verify_jwt = false

[functions.create-role-type]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.funnel-router]
verify_jwt = false

[functions.capture-lead]
verify_jwt = false

[functions.domain-router]
verify_jwt = false