
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supportStorageKey } from '@/lib/supportSession';

const SUPABASE_URL = "https://hddnqgggjjlildufirof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZG5xZ2dnampsaWxkdWZpcm9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MDAzMzQsImV4cCI6MjA2MzM3NjMzNH0.ZvsGyn-c_FqwTg6fSLO8C7pWJcyW4Ev2jWoURq_H_Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supportKey = (() => {
  try { return supportStorageKey(sessionStorage, window.location.pathname, window.location.search); }
  catch { return null; }
})();
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, supportKey ? {
  auth: { storage: sessionStorage, storageKey: supportKey, autoRefreshToken: false, detectSessionInUrl: false }
} : undefined);
